### ISSUE TITLE
Encounter errors compiling libStatGen and fastQValidator on macOS 10.13.3

### ISSUE THREAD

**Issue by kalavattam** [statgen/libStatGen#18]
Dear libStatGen/fastQValidator crew,

I encounter errors when attempting to compile libStatGen and fastQValidator on macOS 10.13.3.

Below, I include text that is printed to my terminal when I attempt to compile libStatGen or fastQValidator (with libStatGen).

I have also installed Fink in order to get apt-get and attempt to compile as described for Ubuntu/Debian; however, I can't get the packages.

Do you have any advice on how to get the library and program up and running?

Thanks for your time,
Kris

[CL_compile_errors_libstatgen_fastQValidator_032418.txt](https://github.com/statgen/libStatGen/files/1845648/CL_compile_errors_libstatgen_fastQValidator_032418.txt)
[terminal_output_032518.txt](https://github.com/statgen/libStatGen/files/1845649/terminal_output_032518.txt)

**Comment by jonathonl** [comment]
I don't see any errors in this output, only warnings. I can see that you are sending a SIGINT to the make process by typing CTRL+C, which is preventing the build from finishing.

**Comment by jonathonl** [comment]
My advice would be to let it finish and check the exit status of make by typing 'echo $?'. If it prints zero, it succeeded.

**Comment by kalavattam** [comment]
Thank you. Echo printed zero, so it likely completed.

I attached the output printed to terminal as well; there are warnings and, at the end, a clang error. However, I'm not sure if it's significant.

Thanks again for your help,
Kris

[CL_output_without_ctrl_c_032518.txt](https://github.com/statgen/libStatGen/files/1845681/CL_output_without_ctrl_c_032518.txt)

**Comment by jonathonl** [comment]
You're getting a link error when building the debug version of fastQValidator. I'm not sure why, but you probably just need to make a clean build of the libStatGen libs. It looks like the release build completed successfully though. Does bin/fastQValidator exist? If so, then that should be good enough to get you going. If you don't need a debug build, just run `make` instead of `make all` in the future.

**Comment by kalavattam** [comment]
Thanks, yes, it seems the release build successfully completed, and bin/fastQValidator exists. I can call fastQValidator from the CL and run it on a test file no problem. I'll play it by ear. Thanks again!
