### ISSUE TITLE
Compilation error: deprecated use of bool in operator++

### ISSUE THREAD

**Issue by bartgrantham** [statgen/libStatGen#23]
Here's the error:
```
g++  -O4 -pipe -Wall -Werror  -Wno-strict-overflow -I../include -I.   -D__ZLIB_AVAILABLE__ -D_FILE_OFFSET_BITS=64 -D__STDC_LIMIT_MACROS  -o obj/Parameters.o -c Parameters.cpp -DVERSION="\"1.0.0\""
Parameters.cpp: In member function 'virtual void LongParameters::Status()':
Parameters.cpp:573:25: error: use of an operand of type 'bool' in 'operator++' is deprecated [-Werror=deprecated]
             legacy_count++;
                         ^~
```

Adding the build flag `-Wno-error=deprecated` resolved this error, but IMHO that's a little dangerous.

**Comment by bartgrantham** [comment]
Oh, I should mention, this is on a more or less bare docker image of `ubuntu:18.04`, with just the packages `build-essential g++ libssl-dev zlib1g-dev` installed.

**Comment by jonathonl** [comment]
This is already fixed in the master branch (see https://github.com/statgen/libStatGen/commit/2f1876e53ac6c31c8e459a4c4543ab801d1dd705).

**Comment by bartgrantham** [comment]
It may be good to issue a new release.  The most recent release is 2 years old.

Why not just `git clone` from master?  Because for reproducibility of scientific results it's important to have explicitly versioned software, and that's easier with official releases rather than whatever git commit was HEAD when the study was done.

**Comment by jonathonl** [comment]
A release is planned. In the meantime, you can use commit hashes for reproducibility. You can download commit archives for building container images in the same way that tagged releases can be downloaded (e.g., https://github.com/statgen/libStatGen/archive/fae4fca874b3b78bf9b61c0eae080c15edd976a4.tar.gz)
