### ISSUE TITLE
incompatibility of vcf/VcfRecordDiscardRules.h unordered_set when compiling with c++11

### ISSUE THREAD

**Issue by Griffan** [statgen/libStatGen#8]
if I enable -std=c++11, g++ complains VcfRecordDiscardRules.h:

 _error: ‘unordered_set’ in namespace ‘std’ does not name a type_

 I assume it's an indication of missing header file.
After I:
_#include\<unordered\_set\>_

it complains:
_/usr/include/c++/4.8/bits/unordered_set.h:33:1: error: expected unqualified-id before ‘namespace’
 namespace std _GLIBCXX_VISIBILITY(default)_

**Comment by mktrost** [comment]
It was a missing header.  Sorry about that.  It have committed the fix.  If you pull the latest changes, it should be fixed.  Thanks for letting me know.

Let me know if you have any additional issues.
