### ISSUE TITLE
Bool used as int, causing condition to be always true

### ISSUE THREAD

**Issue by abadona** [statgen/libStatGen#9]
An extra condition that checks the result of conversion of the input value to boolean always valuates to true, causing compiler to complain:
PedigreeLoader.cpp:641:54: error: comparison of constant '2' with boolean expression is always true
Not a problem for execution, but is a problem if build policy is strict (when warnings are treated as errors).

**Comment by mktrost** [comment]
Fixed with commit: 25b5257a4db5273f44ea5a57a7ae24ce01b4ad68
